spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_category_service
    username: root
    password: root
  liquibase:
    change-log: classpath:/db/changelog/27-01-changelog.xml


  server:
    port: 8081
  jwt:
    secret: 7e\8asddht
    expiration: 990000